# Variables
@baseUrl = http://localhost:3333

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###


# Create a new room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "New Room",
  "description": "This is a new room created via API"
}


###

@roomId = {{createRoom.response.body.$.roomId}}

###
# Get room questions
# @name getRoomQuestions

GET  {{baseUrl}}/rooms/{{roomId}}/questions

###
# Create a new question in a room
# @name createQuestion
POST {{baseUrl}}/rooms/20b8b650-62c7-4286-cca6-c3693b7c8811/questions
Content-Type: application/json

{
    "question": "O que é Vite?"
}